<h2>Iniciar Sesión</h2>
<form action="" name="form1" method="post">
    <input type="hidden" value="1" name="enviar"/>
    <p>
        <label for="">USUARIO:</label>
        <input type="text" name="usuario" value="<?php if(isset($this->datos)) echo $this->datos['usuario'];?>">
    </p>
    <p>
        <label for="">PASSWORD</label>
        <input type="password" name="pass">
    </p>
    <p>        
        <input type="submit" value="Enviar">
    </p>

</form>